# Dependencies
markdown:         redcarpet
pygments:         true

# Setup
title:            Gorilla REPL
url:              http://gorilla-repl.org

author:
  name:           'Jony Hudson'
  url:            http://j-star.org

gems:
  - jekyll-mentions